# Generated by Django 5.0.14 on 2025-10-31 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loan_loan_user_id_2ba89e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date'], name='loan_loan_start_d_df66b2_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'due_date'], name='loan_repaym_loan_id_bb5567_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='loan_repaym_status_440d0c_idx'),
        ),
    ]
