# Generated by Django 5.0.14 on 2025-11-02 09:20

from __future__ import annotations

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def seed_default_scheme(apps, schema_editor):
    LoanScheme = apps.get_model("loan", "LoanScheme")
    Loan = apps.get_model("loan", "Loan")

    default_scheme, _ = LoanScheme.objects.get_or_create(
        name="Legacy Loan Scheme",
        defaults={
            "description": "Auto-generated scheme for existing loans during migration.",
            "lender_name": "Legacy Lender",
            "principal": Decimal("1.00"),
            "interest_rate": Decimal("0.00"),
            "term_months": 1,
            "is_active": False,
        },
    )

    Loan.objects.filter(scheme__isnull=True).update(scheme=default_scheme)
    Loan.objects.filter(total_payable=Decimal("0.00")).update(total_payable=F("principal"))


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanScheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("lender_name", models.CharField(max_length=255)),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        help_text="Simple interest rate for the full loan term as a percentage.",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_schemes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="loan_scheme_is_active_idx"),
                    models.Index(fields=["created_at"], name="loan_scheme_created_at_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_payable",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="loan.loanscheme",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Simple interest rate applied when the loan matures.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("paid", "Paid"),
                    ("closed", "Closed"),
                    ("defaulted", "Defaulted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="term_months",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["scheme", "status"], name="loan_loan_scheme_id_status_idx"),
        ),
        migrations.RunPython(seed_default_scheme, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="loan",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="loan.loanscheme",
            ),
        ),
    ]
