# Generated by Django 5.0.14 on 2025-11-02 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanscheme_and_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loan',
            new_name='loan_loan_scheme__ff0287_idx',
            old_name='loan_loan_scheme_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='loanscheme',
            new_name='loan_loansc_is_acti_f092e3_idx',
            old_name='loan_scheme_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='loanscheme',
            new_name='loan_loansc_created_14afea_idx',
            old_name='loan_scheme_created_at_idx',
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term_months',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
