# Generated by Django 5.0.14 on 2025-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='finance_exp_categor_e43046_idx',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='finance_inc_categor_35050b_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='merchant',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
