# Generated by Django 5.0.14 on 2025-10-31 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarship.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarshipdisbursement',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='scholarship.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarshipdisbursement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['status'], name='scholarship_status_28b0f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scholarshipapplication',
            unique_together={('scholarship', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='scholarshipdisbursement',
            index=models.Index(fields=['user', 'disbursement_date'], name='scholarship_user_id_3d45b0_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipdisbursement',
            index=models.Index(fields=['status'], name='scholarship_status_1bfc32_idx'),
        ),
    ]
