# Generated by Django 5.0.14 on 2025-11-01 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ('deadline', 'name')},
        ),
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='notes',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='renewal_period_months',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipdisbursement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['deadline'], name='scholarship_deadlin_7c67bf_idx'),
        ),
    ]
