# Generated by Django 5.0.14 on 2025-11-02 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_alter_scholarship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='reviewed_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarshipdisbursement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
