# Generated by Django 5.0.14 on 2025-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_alter_scholarship_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
